### ISSUE TITLE
Bot finds an insane amount of misses in FCed replay

### ISSUE THREAD

**Issue by Wieku** [ThereGoesMySanity/osuMissAnalyzer#21]
![image](https://user-images.githubusercontent.com/5307179/121456004-a5009e00-c9a5-11eb-904b-5c843c6a9eb3.png)

Replay: 
[replay-osu_23280_3711329088.zip](https://github.com/ThereGoesMySanity/osuMissAnalyzer/files/6628021/replay-osu_23280_3711329088.zip)

Video of that replay: https://streamable.com/i3he2h

After looking at miss points it seems that Analyzer has a problem with inherited timing points in which beatLength is positive:
![image](https://user-images.githubusercontent.com/5307179/121456262-15a7ba80-c9a6-11eb-80d2-886da7136bf9.png)

**Comment by ThereGoesMySanity** [comment]
It's not a beatLength thing - it's an issue with the legacy slider type used in old maps. None of the actual slider code was written by me so I've been putting off sorting through it to figure exactly what's wrong, especially since issues like these are relatively rare.

I'll see if I can't sort it out tomorrow - hopefully it's something easy

**Comment by Wieku** [comment]
I'm pretty sure it's the beatLength thing, I had the same [issue](https://github.com/Wieku/danser-go/commit/9641b60725f5e1e4baf142cf2d0261a42ee9feb1) in my program. Only the last slider is Catmull so it won't help with that one though.

**Comment by ThereGoesMySanity** [comment]
Ok - you were right, it was the positive beatLength. Fixed now.
